Change Json response format and update sample
koikijs/sigure pull request #6
Opened 2017-01-28 11:41 UTC by da-shino

Update attendances JSON sample

2017-01-30 15:35 UTC, ninja-inc requested changes

2017-01-30 15:35 UTC, ninja-inc commented on test/response/api/v1/attendances/get.json
> +        "href": "http://amam.sample.com/api/v1/attendance_types/5"
[Underscores vs. hyphens in URLs](http://ux.stackexchange.com/questions/9303/underscores-vs-hyphens-in-urls)
[Google](https://support.google.com/webmasters/answer/76329) recommended to use hyphenated URLs.

But for famous public APIs (Facebook, Netflix, etc..) seem using underscored URLs.
[Hyphen, underscore, or camelCase as word delimiter in URIs?](http://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris)

What do you think? @sideroad @nabuchi @taka66

2017-01-30 15:35 UTC, ninja-inc commented on test/response/api/v1/attendances/get.json
> +      "date": "2016-12-26",
It depends on UI side but could we show start and end datetime considering time zone? It's hard for us to know accurate arrival time at the office for not Tokyo office members.

2017-01-30 15:35 UTC, ninja-inc commented on test/response/api/v1/attendances/get.json
> +      "date": "2016-12-26",
like a `"startDateTime": "2016-08-25T10:00:00.000+09:00"`

2017-01-30 22:33 UTC, da-shino commented on test/response/api/v1/attendances/get.json
> +      "date": "2016-12-26",
Exactly, it should not depend time zone but we need more consideration and discussion.a
Currently "date" is one of composite unique key of Attendance model and it has index also. So, if changed start/end model, system should be changed significantly.

Not changed key and just changes format with 0 pad like "YYYY-MM-DD T00:00:00.000+09:00" is no problem at this moment I think.

2017-01-30 22:38 UTC, sideroad commented on test/response/api/v1/attendances/get.json
> +        "href": "http://amam.sample.com/api/v1/attendance_types/5"
I also like hypen.

2017-01-30 23:00 UTC, taka66 commented on test/response/api/v1/attendances/get.json
> +        "href": "http://amam.sample.com/api/v1/attendance_types/5"
hypen +1

2017-02-19 08:15 UTC, closed without merging

2017-02-19 08:15 UTC, da-shino commented
Discard PR due to Architecture change